#!/usr/bin/env python3
"""Generate PostgreSQL to import Gerrit review history into gerrit-go's DB.

Reads deploy/migrate/gerrit_changes_export.json and emits a single transaction
that wipes existing review rows, inserts the 8 changes (with patchsets, votes,
reviewers, change_messages) preserving Gerrit change numbers, and resets the
changes sequence. Account mapping: Gerrit 1000000 -> gerrit-go account id 4.
The projects table is rebuilt separately by a NAS-side script.
"""
import json
import sys

ACC = {1000000: 4}  # gerrit account_id -> gerrit-go accounts.id

# Gerrit NoteDb tags -> gerrit-go change_messages.type vocabulary (see
# web/src/pages/ChangeDetailPage.tsx messageTypeLabel).
TYPE_MAP = {
    "autogenerated:gerrit:newPatchSet": "patchset-uploaded",
    "autogenerated:gerrit:abandon": "abandoned",
    "autogenerated:gerrit:restore": "restored",
    "autogenerated:gerrit:merged": "submitted",
}


def map_msg_type(t, message):
    if t in TYPE_MAP:
        return TYPE_MAP[t]
    # A "comment" whose body is really a label vote -> gerrit-go "vote".
    if t == "comment" and "Code-Review" in (message or ""):
        return "vote"
    return t


def q(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def main(path):
    d = json.load(open(path, encoding="utf-8"))
    out = []
    out.append("-- changes body: run inside a transaction AFTER projects exist")

    for c in d["changes"]:
        num = c["number"]
        owner = ACC[c["owner_gerrit_id"]]
        wip = 1 if c.get("work_in_progress") else 0
        priv = 1 if c.get("private") else 0
        out.append(
            "INSERT INTO changes(number,project,branch,change_id,subject,owner_id,"
            "status,topic,work_in_progress,private,current_ps,created,updated,submitted) VALUES("
            f"{num},{q(c['project'])},{q(c['branch'])},{q(c['change_id'])},{q(c['subject'])},"
            f"{owner},{q(c['status'])},{q(c.get('topic',''))},{wip},{priv},{c['current_ps']},"
            f"{q(c['created'])},{q(c['updated'])},{q(c.get('submitted'))});"
        )
        for ps in c["patchsets"]:
            out.append(
                "INSERT INTO patchsets(change_number,number,commit_sha,author_name,"
                "author_email,message,created) VALUES("
                f"{num},{ps['number']},{q(ps['commit_sha'])},{q(ps['author_name'])},"
                f"{q(ps['author_email'])},{q(ps['message'])},{q(ps['created'])});"
            )
        for v in c.get("votes", []):
            out.append(
                "INSERT INTO votes(change_number,patch_set,account_id,label,value) VALUES("
                f"{num},{v['patch_set']},{ACC[v['account_gerrit_id']]},{q(v['label'])},{v['value']});"
            )
        for r in c.get("reviewers", []):
            out.append(
                "INSERT INTO reviewers(change_number,account_id,added) VALUES("
                f"{num},{ACC[r['account_gerrit_id']]},{q(c['created'])});"
            )
        for m in c.get("messages", []):
            out.append(
                "INSERT INTO change_messages(change_number,patch_set,type,author_id,"
                "message,created) VALUES("
                f"{num},{m['patch_set']},{q(map_msg_type(m['type'], m['message']))},{ACC[m['author_gerrit_id']]},"
                f"{q(m['message'])},{q(m['created'])});"
            )

    out.append("SELECT setval(pg_get_serial_sequence('changes','number'),"
               "(SELECT COALESCE(MAX(number),1) FROM changes));")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1
         else "deploy/migrate/gerrit_changes_export.json")
