package store

import (
	"database/sql"
	"database/sql/driver"
	"strings"

	"github.com/lib/pq"
)

// Driver names supported by the store.
const (
	DriverSQLite   = "sqlite"
	DriverPostgres = "postgres"
)

// IsPostgresDSN reports whether dsn selects the PostgreSQL driver.
func IsPostgresDSN(dsn string) bool {
	return strings.HasPrefix(dsn, "postgres://") || strings.HasPrefix(dsn, "postgresql://")
}

// pgDriverName is the registered wrapper around lib/pq that translates the
// store's "?" placeholders into PostgreSQL's "$n" form.
const pgDriverName = "gerritpg"

func init() {
	sql.Register(pgDriverName, pgDriver{})
}

type pgDriver struct{}

func (pgDriver) Open(name string) (driver.Conn, error) {
	c, err := (&pq.Driver{}).Open(name)
	if err != nil {
		return nil, err
	}
	return pgConn{conn: c}, nil
}

type pgConn struct {
	conn driver.Conn
}

func (c pgConn) Prepare(query string) (driver.Stmt, error) {
	return c.conn.Prepare(rewritePlaceholders(query))
}

func (c pgConn) Close() error              { return c.conn.Close() }
func (c pgConn) Begin() (driver.Tx, error) { return c.conn.Begin() }

// rewritePlaceholders converts "?" placeholders to "$1..$n", skipping question
// marks that appear inside string literals, quoted identifiers or comments.
func rewritePlaceholders(q string) string {
	if !strings.Contains(q, "?") {
		return q
	}
	var b strings.Builder
	b.Grow(len(q) + 8)
	n := 0
	inSingle, inDouble, inLine, inBlock := false, false, false, false
	for i := 0; i < len(q); i++ {
		ch := q[i]
		switch {
		case inLine:
			b.WriteByte(ch)
			if ch == '\n' {
				inLine = false
			}
		case inBlock:
			b.WriteByte(ch)
			if ch == '*' && i+1 < len(q) && q[i+1] == '/' {
				b.WriteByte('/')
				i++
				inBlock = false
			}
		case inSingle:
			b.WriteByte(ch)
			if ch == '\'' {
				// doubled '' is an escaped quote, stay inside the literal
				if i+1 < len(q) && q[i+1] == '\'' {
					b.WriteByte('\'')
					i++
				} else {
					inSingle = false
				}
			}
		case inDouble:
			b.WriteByte(ch)
			if ch == '"' {
				inDouble = false
			}
		default:
			switch {
			case ch == '\'':
				inSingle = true
				b.WriteByte(ch)
			case ch == '"':
				inDouble = true
				b.WriteByte(ch)
			case ch == '-' && i+1 < len(q) && q[i+1] == '-':
				inLine = true
				b.WriteString("--")
				i++
			case ch == '/' && i+1 < len(q) && q[i+1] == '*':
				inBlock = true
				b.WriteString("/*")
				i++
			case ch == '?':
				n++
				b.WriteByte('$')
				b.WriteString(itoa(n))
			default:
				b.WriteByte(ch)
			}
		}
	}
	return b.String()
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[i:])
}

// toPostgresSchema translates the SQLite DDL into PostgreSQL DDL. The schema
// only uses portable types (TEXT/INTEGER); the SQLite-specific parts are the
// AUTOINCREMENT id columns and INTEGER id foreign keys.
func toPostgresSchema(sqlite string) string {
	pg := strings.ReplaceAll(sqlite,
		"INTEGER PRIMARY KEY AUTOINCREMENT",
		"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	pg = strings.ReplaceAll(pg,
		"INTEGER NOT NULL REFERENCES",
		"BIGINT NOT NULL REFERENCES")
	return pg
}

// splitStatements splits SQL text into individual statements on ';'
// boundaries, ignoring semicolons inside single-quoted string literals.
// Empty/whitespace-only fragments are dropped.
func splitStatements(sql string) []string {
	var out []string
	var b strings.Builder
	inSingle := false
	for i := 0; i < len(sql); i++ {
		ch := sql[i]
		switch {
		case inSingle:
			b.WriteByte(ch)
			if ch == '\'' {
				if i+1 < len(sql) && sql[i+1] == '\'' {
					b.WriteByte('\'')
					i++
				} else {
					inSingle = false
				}
			}
		case ch == '\'':
			inSingle = true
			b.WriteByte(ch)
		case ch == ';':
			if s := strings.TrimSpace(b.String()); s != "" {
				out = append(out, s)
			}
			b.Reset()
		default:
			b.WriteByte(ch)
		}
	}
	if s := strings.TrimSpace(b.String()); s != "" {
		out = append(out, s)
	}
	return out
}
